### PR TITLE
fixture and tests for storageDetails and StorageOverview

### PR DESCRIPTION
**Pull request by afreen23**
Added fixture ans test for storage details
Added fixture and test for storageOverview

For storageOverview used the ClusterOverviewContext .

### CODE REVIEW

**Comment by cloudbehl** [comment]
Is `yarn run lint` passing on the PR?

**Comment by cloudbehl** [comment]
@afreen23 can you squash those commit into one.

**Comment by afreen23** [comment]
> Is `yarn run lint` passing on the PR?

yes

**Comment by afreen23** [comment]
> @afreen23 can you squash those commit into one.

tried but so many merge conflicts...created new PR #4

**Pull request closed without merging**
